# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
#  push:
#    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
        cache: 'pipenv'
    - name: Install dependencies
      run: |
        pip install pipenv==2023.12.1
        pipenv install -d
        pip freeze
    - name: Setup config file
      run: |
        cp config_template.json config.json
    - name: Test with pytest
      run: |
        pipenv run pytest --cov=app
        pipenv run coverage report --fail-under=90